### PR TITLE
#205 - remove patch definitions in composer.json that have been commi…

### PR DESCRIPTION
**Pull request by jshinrock**
see comments on https://github.com/thinkshout/bene/issues/205 for verification patches exist in stable versions

to test:

1. clone https://github.com/thinkshout/bene-project/tree/4-fix-install
2. run `./scripts/install.sh -d [some-dir]`
3. observe that installation completes with no patch warnings (would happen before "setup git" user input step)

### CODE REVIEW

**Review by unclegcb — CHANGES_REQUESTED** [review]
```
gcb@gcb (16:50) :~/projects/bp-install(4-fix-install)$ ./scripts/install.sh -d ../bp-install-test
```
got:
screen shot 2018-04-16 at 16 52 21

I think you need to commit the changes that get created in composer.lock as well

**Comment by jshinrock** [comment]
@unclegcb that's a great catch. I forgot to run `composer update` to generate a new lock. Committing now.

**Comment by jshinrock** [comment]
@unclegcb committed composer.lock file. It should also be noted that if you're using the installer listed in step 1, you will have to manually change the branch of the `bene` project being cloned to this branch, otherwise it will keep getting the `8.x-1.x` branch, which has those patches committed. I forgot to mention that in the 1st step. Sorry about that.

**Review by unclegcb — APPROVED** [review]
Ah, yes, that IS important! Maybe the lockfile changes weren't actually necessary?

Anyway, all looks good now.

**Pull request merged**
